<?php

namespace App\Models;

/**
 * Address
 * 
 * @package App\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-06-15, 02:48:16
 */
class Address extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(column="id", type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(column="address_text", type="string", length=300, nullable=false)
     */
    public $address_text;

    /**
     *
     * @var double
     * @Column(column="latitude", type="double", length=16, nullable=true)
     */
    public $latitude;

    /**
     *
     * @var double
     * @Column(column="longitude", type="double", length=16, nullable=true)
     */
    public $longitude;

    /**
     *
     * @var integer
     * @Column(column="user_id", type="integer", length=11, nullable=false)
     */
    public $user_id;

    /**
     *
     * @var integer
     * @Column(column="district_id", type="integer", length=11, nullable=false)
     */
    public $district_id;

    /**
     *
     * @var integer
     * @Column(column="department_id", type="integer", length=11, nullable=false)
     */
    public $department_id;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("alternative_clothing");
        $this->setSource("address");
        $this->belongsTo('user_id', 'App\Models\User', 'id', ['alias' => 'User']);
        $this->belongsTo('district_id', 'App\Models\District', 'id', ['alias' => 'District']);
        $this->belongsTo('department_id', 'App\Models\Department', 'id', ['alias' => 'Department']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'address';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Address[]|Address|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Address|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
