<?php

namespace App\Models;

/**
 * District
 * 
 * @package App\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-06-23, 01:41:08
 */
class District extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(column="id", type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(column="name", type="string", length=300, nullable=true)
     */
    public $name;

    /**
     *
     * @var double
     * @Column(column="latitude", type="double", length=16, nullable=true)
     */
    public $latitude;

    /**
     *
     * @var double
     * @Column(column="longitude", type="double", length=16, nullable=true)
     */
    public $longitude;

    /**
     *
     * @var string
     * @Column(column="postalCode", type="string", length=100, nullable=true)
     */
    public $postalCode;

    /**
     *
     * @var string
     * @Column(column="zipCode", type="string", length=100, nullable=true)
     */
    public $zipCode;

    /**
     *
     * @var string
     * @Column(column="ubigeo", type="string", length=100, nullable=true)
     */
    public $ubigeo;

    /**
     *
     * @var integer
     * @Column(column="department_id", type="integer", length=11, nullable=true)
     */
    public $department_id;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("alternative_clothing");
        $this->setSource("district");
        $this->hasMany('id', 'App\Models\Address', 'district_id', ['alias' => 'Address']);
        $this->belongsTo('department_id', 'App\Models\Department', 'id', ['alias' => 'Department']);
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return District[]|District|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return District|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'district';
    }

}
